server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: IKzD1dVIsIcSpJVRWOOrIETlJZn6Mb5q
            client-secret: BtuSyxwrCL_eU19GbF8q0XRDq_5HjkifwnDyhDGp_P6GlW0oLS1jlUPY_wgWLsrp
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://lesscode.eu.auth0.com/

api:
  key:
    for:
      weather: 462e3718a1cc414ce57e3b3fb213be45
